CC	= g++
AR	= ar
LD	= ld
CFLAGS	= -Wall -m32

LIB_DIR	= libs

#TARGET = tcp_server

OBJECTS += $(SRC:.cpp=.o)

all:$(OBJECTS)

#all:%.o

#%.o: %.cpp
#	$(CC) -c $(CFLAGS) -o $@ $<

#$(OBJECTS):$(SRC)
#	@echo [Compiling files]\ \ \ \ $@
#	$(CC) $(CFLAGS) -c $(SRC)

clean:
	@echo [Cleaning files]\ \ \ \ $@
	rm  -f $(OBJECTS) $(LIB_DIR)/*.as

#
# $(TARGET): $(OBJECTS)
#	@echo [Building Program]\ \ \ \ $@
#	$(CC) $(CFLAGS) -o $@ $(OBJECTS)
