CC	= g++
AR	= ar
LD	= ld
CFLAGS	= -Wall
#-m32
IFLAGS	= -pthread
LIB_DIR	= libs


OBJECTS	= $(SRC:.cpp=.o)

all: $(SRC) $(OBJECTS)



.cpp.o:
	$(CC) $(IFLAGS) $(CFLAGS) -c $< 

#-o $@



clean:
	@echo [Cleaning files]\ \ \ \ $@
	rm  -f $(OBJECTS) $(LIB_DIR)/*.as

#
# $(TARGET): $(OBJECTS)
#	@echo [Building Program]\ \ \ \ $@
#	$(CC) $(CFLAGS) -o $@ $(OBJECTS)
